name: Production Build

on:
  release:
    types: [published]  

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Determine Version
        uses: Stelzi79/action-minver@main-Stelzi79
        id: version
        with:
          auto-increment: patch
          default-pre-release-phase: rc
          tag-prefix: v

      - name: Output Version
        run: |
          echo '### Build Version - ${{ steps.version.outputs.version }}' >> $GITHUB_STEP_SUMMARY
          echo '```${{ steps.version.outputs.version }} ```' >> $GITHUB_STEP_SUMMARY
  build-package:
    name: Build Plugin Package 
    runs-on: ubuntu-latest
    needs: [calculate-version]
    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Compile Sass
        run: cd ./blocks && npm install && npm run sass-compile
      - name: Build React Addon
        run: cd ./gutenberg-addon && npm install && npm run build
      # Artifacts
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: braftonium
          path: |
            ./
            !node_modules
            !gutenberg-addon/node_modules
            !.git
            !.github
          # zip the bundle
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with: 
          name: braftonium
          path: ./dist
      - name: zip bundle
        uses: vimtor/action-zip@v1
        with:
          files: ./dist
          dest: braftonium.zip
      # Get latest release notes, so we can attach assets and pull text
      - name: Fetch Latest Release
        id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}
      - run: echo "Latest Release - ${{ steps.fetch-latest-release.outputs.name }}"

      # upload the bundle zip
      - name: Upload Release Bundle Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch-latest-release.outputs.upload_url }}
          asset_path: ./braftonium.zip
          asset_name: braftonium.zip
          asset_content_type: application/zip
          # send staging release email notification
      - name: Email Release Notification
        uses: brafton/email-release-notes-action@v1.1.1
        with:
          github_token: ${{ github.token }}
          repo_name: platform-app
          product_name: Braftonium Plugin
          email_recipient: pass.shack@brafton.com
          email_password: ${{secrets.EMAIL_PASSWORD}}
          email_username: stewart.snow@brafton.com